### ISSUE TITLE
Options are not passed to template loaders

### ISSUE THREAD

**Issue by agronholm** [marrow/web.template#2]
Unlike one'd think, there is no way to pass options to template loaders. I wanted to pass strict_undefined=True to Mako's Template constructor but that simply wasn't possible. WebCore's documentation says that the options are passed to template renderers, which is also untrue and was never even intended to happen in the first place (AFAIK).

**Comment by agronholm** [comment]
In addition, Mako rendering isn't tested at all in the test suite. This is a serious issue.

**Comment by amcgregor** [comment]
Options can be passed, line 23 of mako_.py will need to be updated to pass the additional options, and line 30 will need to parse out the sensible options and pass them along.

**Comment by amcgregor** [comment]
Should be resolved by f2ffefccc43eba0934eaa2add5e56ac5a10c206a.
